.gitignore, classifai-api/src/main/java/ai/classifai/ClassifaiApp.java, classifai-core/src/main/java/ai/classifai/util/data/FileHandler.java, classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java
=> Minor change for migration to v2.0

classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDbQuery.java, classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioServiceable.java, classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioVerticle.java, classifai-core/src/main/java/ai/classifai/loader/ProjectLoader.java, classifai-core/src/main/java/ai/classifai/router/EndpointRouter.java, classifai-core/src/main/java/ai/classifai/util/ProjectHandler.java
=> API Added for starring and closing project

.github/workflows/build.yml, Dockerfile, classifai-api/src/main/java/ai/classifai/ClassifaiApp.java, classifai-api/src/main/java/ai/classifai/config/DbConfig.java, classifai-core/src/main/java/ai/classifai/MainVerticle.java, classifai-core/src/main/java/ai/classifai/util/ParamConfig.java, classifai-uberjar/pom.xml, readme.md
=> configured for github actions

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/custom.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/build.yml, Dockerfile, classifai-api/src/main/java/ai/classifai/ClassifaiApp.java, classifai-api/src/main/java/ai/classifai/config/DbConfig.java, classifai-core/src/main/java/ai/classifai/MainVerticle.java, classifai-core/src/main/java/ai/classifai/util/ParamConfig.java, classifai-uberjar/pom.xml, readme.md
=> configure for github actions

.github/workflows/build.yml, Dockerfile, classifai-api/src/main/java/ai/classifai/ClassifaiApp.java, classifai-api/src/main/java/ai/classifai/config/DbConfig.java, classifai-core/src/main/java/ai/classifai/router/EndpointRouter.java, classifai-core/src/main/java/ai/classifai/util/ProjectHandler.java
=> Dockerfile detached mode

classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioVerticle.java, classifai-core/src/main/java/ai/classifai/loader/ProjectLoader.java
Solve reloading of project failure
=> load project fix

classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationVerticle.java, classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioVerticle.java, classifai-core/src/main/java/ai/classifai/loader/ProjectLoader.java, classifai-core/src/main/resources/webroot/assets/csv-logo.svg, classifai-core/src/main/resources/webroot/assets/jpeg-logo.svg, classifai-core/src/main/resources/webroot/assets/mp3-logo.svg, classifai-core/src/main/resources/webroot/assets/mp4-logo.svg
=> delete uuid bug fix

readme.md
=> update distro link

classifai-core/src/main/java/ai/classifai/router/EndpointRouter.java
Added one endpoint for get segmentation project meta
=> add getSegProjectMeta endpoint

classifai-core/src/main/java/ai/classifai/router/EndpointRouter.java
sync with changes in v2 main branch for getSegProjectMeta endpoint
=> add endpoint for getSegProjectMeta

classifai-core/src/main/java/ai/classifai/ui/launcher/WelcomeLauncher.java
=> /console/ change

classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationVerticle.java, classifai-core/src/main/java/ai/classifai/database/annotation/bndbox/BoundingBoxDbQuery.java, classifai-core/src/main/java/ai/classifai/database/annotation/seg/SegDbQuery.java, classifai-core/src/main/java/ai/classifai/database/migration/DbMigration.java, classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDbQuery.java, classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioVerticle.java, classifai-core/src/main/java/ai/classifai/loader/ProjectLoader.java, classifai-core/src/main/java/ai/classifai/router/EndpointRouter.java, classifai-core/src/main/java/ai/classifai/selector/annotation/ToolFileSelector.java, classifai-core/src/main/java/ai/classifai/selector/annotation/ToolFolderSelector.java, classifai-core/src/main/java/ai/classifai/util/ProjectHandler.java, classifai-core/src/main/java/ai/classifai/util/collection/ConversionHandler.java, classifai-core/src/main/java/ai/classifai/util/collection/UUIDGenerator.java, classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java
Conversion all index to uuidv4 (randomly generated, most widely used).
change made:
- UUIDGenerator class. (Although the repeated id generation is rare, but i wrote a simple logic for generating new uuid if clashes)
- type of projectid and uuid  Integer -> String. (String type used instead of UUID type is because of json parsing do not accept UUID type which is very frequently used in vertx)
- deletion of AtomicGenerator
- deletion of UUIDseed in portfoliodb
- modification of dbMigration to convert old data index to uuid
To check:
- All functionalities are working
=> Sum v2 UUID conversion

classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioVerticle.java
=> String List instead of Integer List for uuid list

classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationVerticle.java
Hi @kengeSkyMind , for this error fix, due to the structure of v1, its hardly reproducible.
it's very much seen in v2
Can you just run a simple test , focusing on loading project, importing project, reload project, delete some images
try with project of
- 0 image
- 1 image
- a set of images (50 - 300)
to see if anything behave weird from how it should work
if none, do merge and delete this branch. 
Please refer to bug #302 
=> Loading bug fix for #302

classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationVerticle.java
hi @daniellim07 , for the problem of loading project with no data, 
it is seen in both of the bounding box and segmentation from my side
i elaborated in #302 about the issue.
also merge the code and delete the branch if you think this fixed the problem thanks
=> load bug fix

classifai-core/src/main/java/ai/classifai/MainVerticle.java, classifai-core/src/main/java/ai/classifai/database/DbOps.java, classifai-core/src/main/java/ai/classifai/selector/annotation/ToolFileSelector.java, classifai-core/src/main/java/ai/classifai/selector/annotation/ToolFolderSelector.java, classifai-core/src/main/java/ai/classifai/ui/launcher/WelcomeLauncher.java
Error message popup if user start another program while database is currently used.
=> V2 db locked

readme.md
add a brief mentioning about docker is supported
=> Add Docker documentation

classifai-core/src/main/resources/webroot/assets/i18n/image-labelling-cn.json, classifai-core/src/main/resources/webroot/assets/i18n/image-segmentation-cn.json, classifai-core/src/main/resources/webroot/assets/i18n/landing-page-cn.json
=> Chinese term fix

classifai-core/src/main/resources/webroot/assets/i18n/image-segmentation-cn.json
=> region info fix

readme.md
=> v1.2 download link update

readme.md
update latest bitly link provided by @kengeSkyMind
=> update bitly link

classifai-core/src/main/java/ai/classifai/action/parser/AnnotationParser.java, classifai-core/src/main/java/ai/classifai/database/versioning/AnnotationVersion.java
Fix missing boxes when importing project from json file
=> Fix missing boxes when importing project

classifai-core/src/main/java/ai/classifai/selector/project/ProjectFolderSelector.java, classifai-core/src/main/java/ai/classifai/selector/project/ProjectImportSelector.java, classifai-core/src/main/java/ai/classifai/ui/SelectionWindow.java
Fix selection window name for Import and create new project
=> Fix selection window name

classifai-core/src/main/java/ai/classifai/router/V2Endpoint.java
=> Bug fix for #365

classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioVerticle.java, classifai-core/src/main/java/ai/classifai/selector/project/ProjectFolderSelector.java
Label list not imported on the first project. 
=> Fix Label list not imported

.github/workflows/build.yml, .github/workflows/sonar.yml
- Noticed that **v2_alpha** branch was not included in triggering the build & sonar test workflow.
=> Update build & sonar workflow

.github/workflows/auto_pr.yml
- Update description for the automated PR
=> Update automated PR's description

CodeofConduct.md, Contributing.md
First draft of code of conduct and contributing for review.
=> Code of Conduct and Contributing draft

CHANGELOG.md
=> :memo: Added changes to CHANGELOG.md

classifai-api/pom.xml, classifai-cloud/pom.xml, classifai-core/pom.xml, classifai-test/pom.xml, classifai-uberjar/pom.xml, pom.xml, startClassifai.bat, startClassifai.sh
Change all version in pom.xml to `2.0.0-alpha1` 
Also update `startClassifai.bat` and `startClassifai.sh` to reflect changes.
Also the `tool_version` in exported config file is expected to be `2.0.0-alpha1`
=> :bookmark: Update to alpha1 in pom.xml

classifai-core/src/main/java/ai/classifai/router/CloudEndpoint.java
=> 🚑 Remove unnecessary metadata

CHANGELOG.md, readme.md
Update readme and changelog for new release
=> 📝 Update readme and changelog for new release

.github/workflows/auto_pr.yml
- Add Deven as one of the auto PR reviewers as backup.
=> Add Deven as auto pr reviewer

CHANGELOG.md
Add rename features to change log.
Also added api documentation on Gitbook. Haven't Merged.
- Gitbook branch: dev
=> Add rename function to change log

CHANGELOG.md
Update changelog for fixed issue, to keep track in release note 
=> 📝 Update changelog.md

CHANGELOG.md, keyShortcut.md
Details in 
https://github.com/CertifaiAI/Classifai_FrontEnd/pull/194
=> 📝 Added changes to CHANGELOG.md and keyShortcut.md

classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationVerticle.java, classifai-core/src/main/java/ai/classifai/database/annotation/bndbox/BoundingBoxVerticle.java, classifai-core/src/main/java/ai/classifai/database/annotation/seg/SegVerticle.java, classifai-core/src/main/java/ai/classifai/router/EndpointRouter.java, classifai-core/src/main/java/ai/classifai/router/V2Endpoint.java
Somehow, rename api is missing, this PR is adding back reverted commit to v2_alpha. 
Fixes #468 
=> 🐛 Deven fix missing rename

readme.md
@devenyantis @hansheng0512 
- Zoom meeting is created till december 22 using Zoom Certifai account, after that will have to extend or create new links
- Any proposal of changing meeting date/time can be done in the meeting and reaching a mutual concensus
- Community support will remains using classifai channel in discord server
- meeting minutes can be editable by anybody creating an account in hackmd.io
=> 📝 Updated readme with Open Source dev details
